### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by memoryskull** [DrPaulBrewer/single-market-robot-simulator#21]
Hi good day @DrPaulBrewer 
I am a graphic designer and I would like to contribute with the project
I can offer a logo that represents the project.
You can receive the logo without any commitment.
I want to contribute because I like to do it.
Thanks for your time.

Cheers!

**Comment by DrPaulBrewer** [comment]
Thanks for offering.

We've been busy on other things, and I'm not sure we need a logo for this repo at this time.
